feat: completed the vertexai provider integration
traceloop/hub pull request #21
Opened 2024-12-23 19:50 UTC by Gmin2

Completed the integration of vertexAI
 WIP: docs needed to be updated
 
 fix #19 
 /claim #19

2024-12-23 19:57 UTC, nirga reviewed
Thanks @Gmin2! Can you add support for streaming as well?

2024-12-24 09:33 UTC, Gmin2 commented
> Thanks @Gmin2! Can you add support for streaming as well?

Can you review this @nirga, all things done

2024-12-24 15:05 UTC, galkleinman commented
Hey @Gmin2, 

Please copy, the "Definition of Done" defined in the issue to the PR, and mark everything you've done.

2024-12-24 15:26 UTC, Gmin2 commented
> Please copy, the "Definition of Done" defined in the issue to the PR, and mark everything you've done.

hey @galkleinman, what it is meant by `Example Configuration`, for docs i need to send PR to [docs repo](https://github.com/traceloop/docs/tree/main/hub) ?

2024-12-25 10:23 UTC, galkleinman commented
@Gmin2 both in docs and in [here](https://github.com/traceloop/hub/blob/main/config-example.yaml)

2024-12-25 17:58 UTC, Gmin2 commented
can i get a review 
cc @galkleinman @nirga

2024-12-26 16:51 UTC, Gmin2 commented
Implemented function calling, image, video and audio capabilities of the vertexai provider

![Screenshot from 2024-12-26 22-18-45](https://github.com/user-attachments/assets/5506976c-3ac8-4374-b6be-27962b325b7f)

![Screenshot from 2024-12-26 21-48-30](https://github.com/user-attachments/assets/9c323234-5d62-4cb3-9008-3fbb37c47afc)

![Screenshot from 2024-12-26 21-18-09](https://github.com/user-attachments/assets/de04be07-ab2a-4e16-a4a5-b7ad15ca82b6)


Now waiting ffor review

<iframe src="https://giphy.com/embed/um2kBnfo55iW4ZH1Fa" width="480" height="480" style="" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/bombaysoftwares-waiting-mr-bean-still-um2kBnfo55iW4ZH1Fa">via GIPHY</a></p>

2024-12-29 10:50 UTC, galkleinman requested changes
Some major changes requests (before I deep dive into the implementation):
- The whole point of this hub/router, is that you use the OpenAI sdk/api to call w/e provider/model you want. The routing is based on a selected pipeline header, which can either support the functionality (either chat, vision, audio...) or not. While you can multiple pipelines support the same functionality with different models or pipeline for team etc... Each pipeline, should expose the same API as openai exposes and implement it internally. With the current implementation you've changed the routing mechanism of the hub and the exposed api. 
- Tests aren't reproducible since they count on existence of api keys, models and therefore can't be used in CI. use surf-vcr or any preferred network recording solution to create test recordings which will make it reproducible .

2024-12-29 10:50 UTC, galkleinman commented on src/providers/openai/provider.rs
> +        Err(StatusCode::NOT_IMPLEMENTED)
`unimplemented!()`

2024-12-29 10:50 UTC, galkleinman commented on src/routes.rs
> +        // Fall back to header-based routing if needed
this (suspiciously cursor generated) code change the routing behavior of the whole app....

2024-12-31 08:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/traceloop/hub?pullRequest=21) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/traceloop/hub?pullRequest=21) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/traceloop/hub?pullRequest=21) it.</sub>

2025-01-10 15:05 UTC, Gmin2 commented
> The whole point of this hub/router, is that you use the OpenAI sdk/api to call w/e provider/model you want. The routing is based on a selected pipeline header, which can either support the functionality (either chat, vision, audio...) or not. While you can multiple pipelines support the same functionality with different models or pipeline for team etc... Each pipeline, should expose the same API as openai exposes and implement it internally. With the current implementation you've changed the routing mechanism of the hub and the exposed api.

I will do the multimodality part in a seperate PR

> * Tests aren't reproducible since they count on existence of api keys, models and therefore can't be used in CI. use surf-vcr or any preferred network recording solution to create test recordings which will make it reproducible .

Done


Can i get a review for now ?

cc @nirga

2025-01-12 04:04 UTC, nirga reviewed
Hey @Gmin2 can you take a look at the tests? They seem to be failing

2025-01-12 10:42 UTC, Gmin2 commented
> Hey @Gmin2 can you take a look at the tests? They seem to be failing

Fixed now,

2025-05-16 10:25 UTC, closed without merging